#!/bin/bash

if [[ ! -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -d "${UCVM_INSTALL_PATH}/model/uwsfbcvm/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/uwsfbcvm/lib:${DYLD_LIBRARY_PATH} ./test_uwsfbcvm
    exit
  fi
fi

env DYLD_LIBRARY_PATH=../src:${DYLD_LIBRARY_PATH} ./test_uwsfbcvm
