name: uwsfcvm-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  uwsfcvm-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/uwsfcvm/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/uwsfcvm/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei
        path: ucvm
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'uwsfcvm'
         target-model: 'uwsfcvm'
         target-branch: 'testMei'
#   - name: Start SSH via Ngrok
#     if: ${{ success() }}
#     uses: luchihoratiu/debug-via-ssh@main
#     with:
#           NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#           NGROK_TIMEOUT: 3000
#           SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock uwsfcvm away
      run: (rm -rf $RUNNER_WORKSPACE/uwsfcvm/ucvm/work/model/uwsfcvm)
      shell: bash
### build uwsfcvm from github 
    - name: checkout uwsfcvm main
      uses: actions/checkout@v2
      with: 
        path: uwsfcvm
    - name: move it to the right location
      run: (mv uwsfcvm $RUNNER_WORKSPACE/uwsfcvm/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build uwsfcvm as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/uwsfcvm/ucvm/work/model/uwsfcvm; ./.github/scripts/uwsfcvm-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test uwsfcvm with ucvm
      run: (cd $RUNNER_WORKSPACE/uwsfcvm/ucvm/work/model/uwsfcvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/uwsfcvm-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test uwsfcvm under ucvm
      run: (cd $RUNNER_WORKSPACE/uwsfcvm/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash



